Set operators for UD60x18 and SD59x18
PaulRBerg/prb-math pull request #168
Opened 2023-02-23 22:12 UTC by Amxx

Note: this can't pass checks until prettier supports user defined operators.

2023-02-23 22:17 UTC, PaulRBerg commented
Thanks, Hadrien! I will review this during the weekend.

Indeed, the link checks will pass only after `prettier-plugin-solidity` and `@solidity-parser/parser` add support for Solidity v0.8.19 and UDVT operators:

https://github.com/solidity-parser/parser/issues/80

2023-02-27 22:36 UTC, fvictorio commented
@PaulRBerg Let me know if that's urgent for you. I opened an issue in Prettier Solidity but didn't implement it yet.

2023-02-28 07:38 UTC, PaulRBerg commented
Thanks, @fvictorio.

This is relatively urgent, indeed, as we're prepping up for an audit of a code base that uses PRBMath, and it would be great to have this PR merged in before the audit starts (we'd prefer to use UDVT operators).

2023-02-28 18:20 UTC, PaulRBerg requested changes
Just finished reviewing this. Overall it looks pretty good!

Besides the alphabetical ordering issues mentioned below, there's just one other thing that needs to be added:

Duplicate the revert test in `div` and `mul` so that both the function and the operator are covered.

2023-02-28 18:24 UTC, Amxx commented
I did not realize that they were ordered alphabetically.

Note that the order I used for operator is the one provided by solidity in its documentation.
(ordering is transparent to me, I let you do how you prefer)

2023-02-28 18:41 UTC, PaulRBerg commented
No worries! Thanks for the additional color.

2023-03-01 11:52 UTC, fvictorio commented
Done: https://github.com/prettier-solidity/prettier-plugin-solidity/releases/tag/v1.1.3

2023-03-01 14:15 UTC, PaulRBerg commented
Thank you so, so much, @fvictorio.

But now I just realized that the issue wasn't due to `prettier-plugin-solidity`, as I have recently moved this project to use `forge fmt` instead.

The issue is with Solhint :(

This command fails:

```sh
yarn solhint "{src,test}/**/*.sol"
```

Any chance you could also bump the Solidity parser in Solhint to fix this? 🙏

2023-03-09 11:32 UTC, PaulRBerg commented
CI passed after upgrading to the latest version of Solhint. Merging now.

Thanks for your contribution, Hadrien!

2023-03-09 11:32 UTC, PaulRBerg approved these changes
CI passed after upgrading to the latest version of Solhint. Merging now.

Thanks for your contribution, Hadrien!

2023-03-09 11:32 UTC, merged