Updated Security Section
PaulRBerg/prb-math pull request #242
Opened 2024-08-07 12:29 UTC by 0xJayPi

### Description
Added reference to security reviews of the codebase

### Changes
- Modified `README.md`
- Added `audits/AUDITS.md`

### Related Issue
Related to https://github.com/PaulRBerg/prb-math/issues/197

2024-08-13 11:19 UTC, PaulRBerg requested changes
Hi @0xJayPi, thanks for your PR. I have reviewed it now and I want to make some changes, but it looks like I am not allowed to do that:

> ! [rejected]        main -> main (non-fast-forward)

Could you please give me permission to push to your branch?

Alternatively, please make your changes on a new branch (not on `main`). That will make it work.

2024-08-13 11:19 UTC, PaulRBerg commented on audits/AUDITS.md
The standard place to place security-related information is the `SECURITY.md` file. Let's move this file over there.

2024-08-13 23:35 UTC, 0xJayPi commented
Apologies, first time I don't create a branch for simplicity. I'll make the needed changes next week (on vacations leave right now)

2024-08-19 10:40 UTC, 0xJayPi commented
@PaulRBerg. I just sent you an invite to my repo. If still needed, I can just move forward and do a new branch and move everything there. Please let me know

2024-08-19 13:57 UTC, PaulRBerg commented
@0xJayPi I would prefer not to be added as a collaborator to your repo. Please just create a new PR with a different branch. Thank you.

2024-08-19 19:05 UTC, closed without merging